### ISSUE TITLE
license 추가

### ISSUE THREAD

**Issue by ejalice** [iDrogba/MZSoft#22]
## Todo
- [ ]Home View에 settings 버튼 추가
- [ ]Settings View 생성
- [ ]SettingsView - HomeView 연결
- [ ]SettingsView에 License 추가
